### ISSUE TITLE
Does not handle redirections

### ISSUE THREAD

**Issue by Pelix1000** [stape-io/http-lookup-variable#1]
I was trying to use this variable to read cells in a Google Sheet that works as a web app. But Google makes a redirection whenever ContentService is used in app scripts and this variable just returns the 302 but does not go for the second iteration to achieve final response. I wish you make it viable in redirections. 

(https://developers.google.com/apps-script/guides/content#redirects)

**Comment by Bukashk0zzz** [comment]
Sorry but there no support of "follow redirects" in sGTM https://developers.google.com/tag-platform/tag-manager/server-side/api#sendhttprequest

But you can use our spreadsheet-variable for your task  https://github.com/stape-io/spreadsheet-variable

**Comment by Pelix1000** [comment]
Thanks for your answer.

Well, I first did tests with HTTP Request tag, the one that comes by
default with ss GTM, and it supports "follows directs" (see image below I
captured from the debug view), however I´m trying to parse the "response
body", that's why I was trying to use the variable HTTP Lookup.

If you can give me a light on it I will be very grateful :).

[image: image.png]

**Comment by Bukashk0zzz** [comment]
I added support of follow redirect.

Can you try now https://github.com/stape-io/http-lookup-variable/blob/develop/template.tpl

**Comment by Bukashk0zzz** [comment]
You need to use this pre release template https://github.com/stape-io/http-lookup-variable/blob/develop/template.tpl

**Comment by Pelix1000** [comment]
It worked perfectly, you´re such an angel to me! 👍😊😇🤗

**Comment by Bukashk0zzz** [comment]
Have a nice weekend :)
