### ISSUE TITLE
Use templateDataStorage

### ISSUE THREAD

**Issue by Larsfriishansen** [stape-io/http-lookup-variable#3]
It would be nice to ise Template Storage, so we don't make a request to the endpoint every time the variable is used. 

Docs:
https://developers.google.com/tag-platform/tag-manager/server-side/api#templatedatastorage

**Comment by Bukashk0zzz** [comment]
Hi,

Done https://github.com/stape-io/http-lookup-variable/commit/28b8d3a2b25bb542cbe3bca0ad913bc6e1a8f9fd
